### ISSUE TITLE
多余文件删除和模版困惑

### ISSUE THREAD

**Issue by hjkl950217** [2881099/FreeSql.Tools#15]
[class1.cs](https://github.com/2881099/FreeSql.Tools/blob/920e7ab2fe9989d075de7f9dab1a936411881555/FreeSql.Tools.WinForm/Class1.cs)

看起来这个文件是测试用的，可以删除或是改名标记一波？

另外想问一下，我最近想利用自定义模版功能改一个自己的模版，除了razor的用法以外，还想看看有那些基本属性和方法可以拿来使用的。
翻了一下代码，似乎只有‘FreeSql.Tools.DSkin\Models\RazorModel.cs’，但最早这个工具是dotnet tool，没有.net core版本的哇？ `FreeSql.Tools.DSkin`是Framework版本的

**Comment by 2881099** [comment]
class1.cs 是测试文件

[FreeSql.Tools.WinForm](https://github.com/2881099/FreeSql.Tools/tree/920e7ab2fe9989d075de7f9dab1a936411881555/FreeSql.Tools.WinForm) 这个项目是 .net framework 的

这个仓储下都是 .net framework 的

dotnet tool 项目在 https://github.com/dotnetcore/FreeSql/tree/master/Extensions/FreeSql.Generator

**Comment by hjkl950217** [comment]
好的。。  

这个文件名看着好像未删除的，看内容也不像是测试，搜索了一下没有地方用才能知道.
建议改成 TestEntity.cs吧

**Comment by hjkl950217** [comment]
其他的没什么。，issue我先关拉~
